### PR TITLE
Auth alt proposal

### PR DESCRIPTION
**Pull request by Saalvage**
This should work just as well and is designed better

### CODE REVIEW

**Comment by JohHub** [comment]
This immediately throws an exception for every component that tries to render something based on the loggend in condition since it will always try to render before the call has completed. That doesn't sound like good design.

**Comment by Saalvage** [comment]
The design is not bad, if we had the time we should make the distinction between "logged in" "logged out" and "unknown" everywhere, but due to time constraints I'll budge

**Comment by JohHub** [comment]
I'm not too happy about forcing the entire page to reload. But I guess since it only occurs once its fine

**Comment by Saalvage** [comment]
I feel like I'm still not fully understanding how exactly your proposal triggers any rerender at all. Is a rerender automatically triggered when `OnInitialized` returns?

**Comment by JohHub** [comment]
Ah I kind of missed 

> This immediately throws an exception for every component that tries to render something based on the `LoggedIn` condition since it will always try to render before the call has completed. That doesn't sound like good design.

I kind of missed the Loaded flag. Lets just move with this.

**Comment by JohHub** [comment]
> I feel like I'm still not fully understanding how exactly your proposal triggers any rerender at all. Is a rerender automatically triggered when `OnInitialized` returns?

More or less yes. After `OnInitialized`, `CallOnParametersSetAsync` is called which calls `StateHasChanged`

**Review by JohHub — APPROVED** [review]

**Pull request merged**
